defmodule Qpg.Integrations.GoogleClassroom do
  alias Qpg.Logging

  @endpoint "https://classroom.googleapis.com/v1"

  def create_material(attrs) do
    course_id = attrs["course_id"]
    payload = material_payload(attrs)

    Logging.info("integrations.google_classroom.create_material.started", %{
      course_id: course_id,
      title: payload.title,
      has_attachment: payload.materials != []
    })

    case access_token() do
      nil ->
        # Without OAuth in v1 we return the exact payload that would be posted.
        # This keeps the UI integration testable without pretending an upload
        # happened in Google Classroom.
        Logging.warning("integrations.google_classroom.create_material.prepared_without_token", %{
          course_id: course_id,
          title: payload.title
        })

        {:ok, %{status: "prepared", course_id: course_id, payload: payload}}

      token ->
        post_material(course_id, token, payload)
    end
  end

  defp material_payload(attrs) do
    title = attrs["title"] || "Generated Question Paper"
    description = attrs["description"] || "Question paper generated by Question Paper Studio."
    attachment_url = attrs["attachment_url"]

    materials =
      if attachment_url in [nil, ""] do
        []
      else
        [%{link: %{url: attachment_url}}]
      end

    %{
      title: title,
      description: description,
      state: attrs["state"] || "DRAFT",
      materials: materials
    }
  end

  defp post_material(course_id, token, payload) do
    body = Jason.encode!(payload)
    url = "#{@endpoint}/courses/#{URI.encode_www_form(course_id)}/courseWorkMaterials"

    Logging.info("integrations.google_classroom.http.request", %{
      course_id: course_id,
      title: payload.title,
      has_token: token not in [nil, ""]
    })

    request =
      Finch.build(
        :post,
        url,
        [
          {"authorization", "Bearer #{token}"},
          {"content-type", "application/json"}
        ],
        body
      )

    case Finch.request(request, Qpg.Finch) do
      {:ok, %{status: status, body: response_body}} when status in 200..299 ->
        Logging.info("integrations.google_classroom.http.created", %{
          course_id: course_id,
          status: status
        })

        {:ok, %{status: "created", response: decode_json(response_body)}}

      {:ok, %{status: status, body: response_body}} ->
        Logging.error("integrations.google_classroom.http.error_status", %{
          course_id: course_id,
          status: status,
          response: decode_json(response_body)
        })

        {:error, %{status: status, response: decode_json(response_body)}}

      {:error, reason} ->
        Logging.error("integrations.google_classroom.http.request_failed", %{
          course_id: course_id,
          reason: inspect(reason)
        })

        {:error, %{status: "request_failed", reason: inspect(reason)}}
    end
  end

  defp access_token do
    System.get_env("GOOGLE_CLASSROOM_ACCESS_TOKEN")
  end

  defp decode_json(body) do
    case Jason.decode(body) do
      {:ok, decoded} -> decoded
      {:error, _} -> body
    end
  end
end
